# Generated by Django 4.0.3 on 2022-07-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_M_ADL',
            fields=[
                ('id_adl', models.AutoField(primary_key=True, serialize=False)),
                ('t_modulo', models.CharField(max_length=20)),
                ('s_modulo', models.CharField(max_length=20)),
                ('n_check', models.IntegerField()),
                ('score_m', models.IntegerField()),
                ('i_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='C_M_CT',
            fields=[
                ('id_ct', models.AutoField(primary_key=True, serialize=False)),
                ('t_modulo', models.CharField(max_length=20)),
                ('s_modulo', models.CharField(max_length=20)),
                ('n_check', models.IntegerField()),
                ('score_m', models.IntegerField()),
                ('i_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='C_M_MBM',
            fields=[
                ('id_mbm', models.AutoField(primary_key=True, serialize=False)),
                ('t_modulo', models.CharField(max_length=20)),
                ('s_modulo', models.CharField(max_length=20)),
                ('n_check', models.IntegerField()),
                ('score_m', models.IntegerField()),
                ('i_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='C_M_ME',
            fields=[
                ('id_me', models.AutoField(primary_key=True, serialize=False)),
                ('t_modulo', models.CharField(max_length=20)),
                ('s_modulo', models.CharField(max_length=20)),
                ('n_check', models.IntegerField()),
                ('score_m', models.IntegerField()),
                ('i_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='C_M_MHYS',
            fields=[
                ('id_mhys', models.AutoField(primary_key=True, serialize=False)),
                ('t_modulo', models.CharField(max_length=20)),
                ('s_modulo', models.CharField(max_length=20)),
                ('n_check', models.IntegerField()),
                ('score_m', models.IntegerField()),
                ('i_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='C_M_SEADLS',
            fields=[
                ('id_seadls', models.AutoField(primary_key=True, serialize=False)),
                ('t_modulo', models.CharField(max_length=20)),
                ('s_modulo', models.CharField(max_length=20)),
                ('n_check', models.IntegerField()),
                ('score_m', models.IntegerField()),
                ('i_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='C_USER',
            fields=[
                ('id_u', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_u', models.CharField(max_length=20)),
                ('edad_u', models.IntegerField()),
                ('correo_u', models.EmailField(max_length=20)),
                ('profesion_u', models.CharField(max_length=20)),
                ('sexo_u', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fnaci', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='F_FINALIZADO',
            fields=[
                ('id_ff', models.AutoField(primary_key=True, serialize=False)),
                ('score_ff', models.IntegerField()),
                ('fc_ff', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FORMULARIO',
            fields=[
                ('id_fp', models.AutoField(primary_key=True, serialize=False)),
                ('f_c_f', models.DateField()),
                ('score_t_f', models.IntegerField()),
                ('t_i_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GRAFICOS_FF',
            fields=[
                ('id_g', models.AutoField(primary_key=True, serialize=False)),
                ('g_ff', models.IntegerField()),
                ('g_v_d', models.IntegerField()),
                ('g_f_d', models.IntegerField()),
                ('g_pr', models.IntegerField()),
                ('g_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id_pdf', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RC_USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='V_C_U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_u_c', models.EmailField(max_length=20)),
            ],
        ),
    ]
