# Generated by Django 4.0.3 on 2022-07-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinson', '0003_alter_creacion_de_user_correo_u_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crear_usuario',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id_u', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_u', models.CharField(max_length=20, verbose_name='Nombre de Usuario')),
                ('edad_u', models.IntegerField(verbose_name='Edad de Usuario')),
                ('correo_u', models.EmailField(max_length=20, verbose_name='Correo de Usuario')),
                ('profesion_u', models.CharField(max_length=20, verbose_name='Profesion de Usuario')),
                ('sexo_u', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero de Usuario')),
                ('fnaci', models.DateField(verbose_name='Fecha de Nacimiento de  Usuario')),
            ],
        ),
        migrations.RenameModel(
            old_name='RECUPERACION_CONTRASEÑA_USER',
            new_name='Recuperacion_contraseña',
        ),
        migrations.RenameModel(
            old_name='VALIDACION_CORREO_USUARIOS',
            new_name='Validacion_de_usuario',
        ),
        migrations.DeleteModel(
            name='CREACION_DE_USER',
        ),
        migrations.AddField(
            model_name='creacion_modulo_mbm',
            name='nombre_check',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre de Modulo 0'),
        ),
        migrations.AddField(
            model_name='creacion_modulo_mbm',
            name='nombre_check1',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre de Modulo 1'),
        ),
        migrations.AddField(
            model_name='creacion_modulo_mbm',
            name='nombre_check2',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre de Modulo 2'),
        ),
        migrations.AddField(
            model_name='creacion_modulo_mbm',
            name='nombre_check3',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre de Modulo 3'),
        ),
        migrations.AddField(
            model_name='creacion_modulo_mbm',
            name='nombre_check4',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre de Modulo 4'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_ct',
            name='i_m',
            field=models.IntegerField(verbose_name='Interaccion de Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_ct',
            name='n_check',
            field=models.IntegerField(verbose_name='Numero de Checkbox'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_ct',
            name='s_modulo',
            field=models.CharField(max_length=20, verbose_name='Subtitulo del Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_ct',
            name='score_m',
            field=models.IntegerField(verbose_name='Score de Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_ct',
            name='t_modulo',
            field=models.CharField(max_length=20, verbose_name='Titulo del Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_me',
            name='i_m',
            field=models.IntegerField(verbose_name='Interaccion de Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_me',
            name='n_check',
            field=models.IntegerField(verbose_name='Numero de Checkbox'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_me',
            name='s_modulo',
            field=models.CharField(max_length=20, verbose_name='Subtitulo del Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_me',
            name='score_m',
            field=models.IntegerField(verbose_name='Score de Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_me',
            name='t_modulo',
            field=models.CharField(max_length=20, verbose_name='Titulo del Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_mhys',
            name='i_m',
            field=models.IntegerField(verbose_name='Interaccion de Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_mhys',
            name='n_check',
            field=models.IntegerField(verbose_name='Numero de Checkbox'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_mhys',
            name='s_modulo',
            field=models.CharField(max_length=20, verbose_name='Subtitulo del Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_mhys',
            name='score_m',
            field=models.IntegerField(verbose_name='Score de Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_mhys',
            name='t_modulo',
            field=models.CharField(max_length=20, verbose_name='Titulo del Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_seadls',
            name='i_m',
            field=models.IntegerField(verbose_name='Interaccion de Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_seadls',
            name='n_check',
            field=models.IntegerField(verbose_name='Numero de Checkbox'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_seadls',
            name='s_modulo',
            field=models.CharField(max_length=20, verbose_name='Subtitulo del Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_seadls',
            name='score_m',
            field=models.IntegerField(verbose_name='Score de Modulo'),
        ),
        migrations.AlterField(
            model_name='creacion_modulo_seadls',
            name='t_modulo',
            field=models.CharField(max_length=20, verbose_name='Titulo del Modulo'),
        ),
    ]
