# Generated by Django 4.0.3 on 2022-07-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinson', '0006_remove_creacion_modulo_mbm_t_modulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creacion_modulo_mbm',
            options={'ordering': ['id_mbm']},
        ),
    ]
